.PHONY: generate-go
generate-go:
	@bash "./scripts/generate-go.sh"
.PHONY: generate-go
generate-rust:
	@bash "./scripts/generate-rust.sh"
.PHONY: generate
generate:
	@make generate-go
	@make generate-rust