// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	_map "github.com/farhanaltariq/protomessager/go/map"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// MapServiceClient is an autogenerated mock type for the MapServiceClient type
type MapServiceClient struct {
	mock.Mock
}

// Hello provides a mock function with given fields: ctx, in, opts
func (_m *MapServiceClient) Hello(ctx context.Context, in *_map.A, opts ...grpc.CallOption) (*_map.B, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Hello")
	}

	var r0 *_map.B
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *_map.A, ...grpc.CallOption) (*_map.B, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *_map.A, ...grpc.CallOption) *_map.B); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*_map.B)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *_map.A, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMapServiceClient creates a new instance of MapServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMapServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MapServiceClient {
	mock := &MapServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
