// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	_map "github.com/farhanaltariq/protomessager/go/map"

	mock "github.com/stretchr/testify/mock"
)

// MapServiceServer is an autogenerated mock type for the MapServiceServer type
type MapServiceServer struct {
	mock.Mock
}

// Hello provides a mock function with given fields: _a0, _a1
func (_m *MapServiceServer) Hello(_a0 context.Context, _a1 *_map.A) (*_map.B, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Hello")
	}

	var r0 *_map.B
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *_map.A) (*_map.B, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *_map.A) *_map.B); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*_map.B)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *_map.A) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedMapServiceServer provides a mock function with given fields:
func (_m *MapServiceServer) mustEmbedUnimplementedMapServiceServer() {
	_m.Called()
}

// NewMapServiceServer creates a new instance of MapServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMapServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MapServiceServer {
	mock := &MapServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
