// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeMapServiceServer is an autogenerated mock type for the UnsafeMapServiceServer type
type UnsafeMapServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedMapServiceServer provides a mock function with given fields:
func (_m *UnsafeMapServiceServer) mustEmbedUnimplementedMapServiceServer() {
	_m.Called()
}

// NewUnsafeMapServiceServer creates a new instance of UnsafeMapServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeMapServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeMapServiceServer {
	mock := &UnsafeMapServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
