// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct A {
    #[prost(string, tag = "1")]
    pub req: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct B {
    #[prost(string, tag = "1")]
    pub res: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
