// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MapRequest {
    #[prost(string, tag = "1")]
    pub alt: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub lat: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub lon: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MapResponse {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub alt: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub lat: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub lon: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
